### ISSUE TITLE
SpotifyAPI doesn't work on recent Spotify version.

### ISSUE THREAD

**Issue by JeffreyO** [LPardue/SpotifyStatusApplet#9] opened 2018-04-26 23:46 UTC
I've noticed that the applet suddenly stopped working and found that the issue was with SpotifyAPI. I found that your applet always gets passed a null value when requesting what song is playing even while a song is playing.

**Comment by LPardue** [comment] 2018-04-27 17:50
Hi,

Thanks for raising the issue. It's been a long time since I needed to
personally use the applet. I'll see if I can reconstruct a test environment.

The last time something like this happened it was because the applet failed
to get credentials when it starts. It does so by requesting a specific
track from Spotify, it might be that the track has been removed from the
catalog (that was the cause of failure last time).

**Comment by JeffreyO** [comment] 2018-04-27 23:06
I'm running the SpotifyAPI Test application from here https://github.com/McNull/spotify-local-api/tree/master/SpotifyLocalAPI
and it doesn't even recognize that Spotify has is even running. Afterwards, it simply says there isn't a song playing.

**Comment by JeffreyO** [comment] 2018-04-28 02:39
I'm currently trying out https://github.com/JohnnyCrazy/SpotifyAPI-NET and am modifying program.cs to get the library working with it. 
It works with the current version of Spotify and has useful stuff like track.isAd() that will keep the app from crashing without me having to implement a try-catch block.

So far so good.

**Comment by JeffreyO** [comment] 2018-04-29 03:27
I just got done and am about to merge the changes.

**Comment by JeffreyO** [comment] 2018-04-29 04:26
The pull request is now posted.
If you want to test everything out and verify that it works on your computer, the built binaries are below in a ZIP file. The README.txt in ReleaseFiles needs to be updated to reflect to be the same as the one located in the root folder.
[SpotifyStatusApplet 1.3 Built by JeffreyO.zip](https://github.com/LPardue/SpotifyStatusApplet/files/1958426/SpotifyStatusApplet.1.3.Built.by.JeffreyO.zip)

**Comment by LPardue** [comment] 2018-04-29 15:43
Thanks again @JeffreyO, you clearly put a lot of work into the PR. It is now merged into master and I will work on hosting a v1.3 package on my website.

Closing the issue now that it seems to have been addressed.

**Closed as completed by LPardue** 2018-04-29 15:43 UTC
